# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "proxmox_node" {
  type    = string
  default = "homelab"
}

locals {
    proxmox_username= vault("secrets/proxmox", "username")
}

locals {
    proxmox_password = vault("secrets/proxmox", "password")
}

locals {
    proxmox_url = vault("secrets/proxmox", "url")
}
locals {
    date = formatdate("YYYYMMDD-hhmm", timeadd(timestamp(), "8h"))
}

variable "ssh_username" {
  type    = string
  default = "ubuntu"
}
# user-data identity password
variable "ssh_password" {
  type    = string
  default = "ubuntu"
}


variable "iso_file" {
  type    = string
  default = "local:iso/ubuntu-20.04.2-live-server-amd64.iso"
}




# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "proxmox" "ubuntu" {
  username             = "${local.proxmox_username}"
  password             = "${local.proxmox_password}"
  proxmox_url          = "${local.proxmox_url}"
  node                 = "${var.proxmox_node}"

  boot_command = ["<enter><enter><f6><esc><wait>", "autoinstall ds=nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/", "<enter><wait>"]
  boot_wait    = "3s"

  http_directory           = "cloud-init"
  #http_interface           = "ppp0"
  http_interface           = "en0"
  insecure_skip_tls_verify = true
  iso_file                 = "${var.iso_file}"
  #unmount_iso              = true

  os                       = "l26"
  cores                    = "2"
  memory                   = "4096"
  disks {
    disk_size         = "20G"
    storage_pool      = "local-lvm"
    storage_pool_type = "lvm"
    type              = "scsi"
  }
  scsi_controller      = "virtio-scsi-pci"

  network_adapters {
    bridge = "vmbr0"
  }

  qemu_agent           = true
  template_name        = "Ubuntu-template-${local.date}"
  template_description = "Ubuntu 20.04 x86_64 template built with packer on ${local.date}"

  ssh_username         = "${var.ssh_username}"
  ssh_password         = "${var.ssh_password}"
  ssh_timeout          = "20m"


}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.proxmox.ubuntu"]

  provisioner "shell" {
    inline = [
      "sudo truncate -s 0 /etc/machine-id",
      "exit 0",
      ]
  }

}
